### ISSUE TITLE
Consider writing tests in WorDBless

### ISSUE THREAD

**Issue by szepeviktor** [sitecrafting/greg#3]
This is revolutionary 🚀 
https://github.com/Automattic/wordbless

You don't need a database **and the WordPress test suite** for running tests.
No need for `bin/setup-wordpress.sh`

**Comment by acobster** [comment]
I am not planning on mocking the WP database.

Greg's core logic is purely functional and has no dependencies, not even WP core. Therefore, the same is true of unit tests.

For components that can't be unit-tested, I want to test a real integration, not a fake/naive implementation of the WP core logic.
